# Generated by Django 5.1.5 on 2025-03-11 19:27

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('ongoing', 'En emisión'), ('completed', 'Finalizado'), ('hiatus', 'En pausa')], default=('ongoing', 'En emisión'), max_length=20)),
                ('genre', models.CharField(choices=[('Any', 'Ninguno'), ('Adventure', 'Aventura'), ('Science fiction', 'Ciencia ficción'), ('Comedy', 'Cómedia'), ('Sport', 'Deporte'), ('Fancy', 'Fantasia'), ('book', 'Misterio'), ('Drama', 'Drama'), ('Action', 'Acción'), ('Daily life', 'Vida cotidiana'), ('Romance', 'Romance'), ('Paranormal', 'Paranormal'), ('Suspense', 'Suspenso'), ('Terror', 'Terror'), ('Superheroes', 'Superhéroes'), ('Historical', 'Histórico'), ('Informative', 'Informativo'), ('Touching', 'Conmovedor')], default=('novel', 'Novela'), max_length=30)),
                ('subgenre', models.CharField(choices=[('Any', 'Ninguno'), ('Cyberpunk', 'Ciberpunk'), ('Science fiction', 'Bélico'), ('Police', 'Policial'), ('Meccas', 'Mecas')], default=('Any', 'Ninguno'), max_length=30)),
                ('format_type', models.CharField(choices=[('novel', 'Novela'), ('manhwa', 'Manhwa'), ('comic', 'Cómic'), ('manga', 'Manga'), ('story', 'Cuento'), ('book', 'Libro')], default=('comic', 'Cómic'), max_length=10)),
                ('description', models.TextField(default='')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('views', models.IntegerField(default=2000)),
                ('likes', models.PositiveIntegerField(default=500)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comics', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Título del Capítulo', max_length=255)),
                ('chapter_number', models.PositiveIntegerField(default=1)),
                ('content', models.TextField(default='Content')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('image_folder', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='chapters/')),
                ('comic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='comics.comic')),
            ],
            options={
                'ordering': ['chapter_number'],
            },
        ),
        migrations.CreateModel(
            name='SubGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgenres', to='comics.genre')),
            ],
        ),
    ]
